
import React from 'react';
import { useParams } from 'react-router-dom';

const CarDetails = () => {
  const { carId } = useParams();

  
  const cars = {
    '1': { name: 'Ford Mustang', description: 'The first-generation Ford Mustang was manufactured by Ford from March 1964 until 1973. The introduction of the Mustang created a new class of automobiles known as pony cars. The Mustangs styling, with its long hood and short deck, proved wildly popular and inspired a host of competition It was introduced on April 17, 1964, as a hardtop and convertible, with the fastback version following in August 1964. Upon introduction, the Mustang, sharing its platform with the Falcon, was slotted into the compact car segment.The first-generation Mustangs grew in overall dimensions and engine power with each revision. The 1971 model featured a drastic redesign. After an initial surge, sales steadily declined, and Ford began working on a new generation Mustang. With the onset of the 1973 oil crisis, Ford was prepared, having already designed the smaller Mustang II for the 1974 model year. This new car shared no components with preceding models.', image: 'car-4445171_1280.jpg' },
    '2': { name: 'Beetle', description: 'The Volkswagen Beetle, officially the Volkswagen Type 1,[a] is a small car produced by the German company Volkswagen from 1938 to 2003.[b] One of the most iconic cars in automotive history, the Beetle is noted for its distinctive shape. Its production period of 65 years is the longest of any single generation of automobile,[c] and its total production of over 21.5 million is the most of any car of a single platform.The Beetle was conceived in the early 1930s. The leader of Nazi Germany, Adolf Hitler, decided there was a need for a peoples car—an inexpensive, simple, mass-produced car—to serve Germanys new road network, the Reichsautobahn. The German engineer Ferdinand Porsche and his design team began developing and designing the car in the early 1930s. But the fundamental design concept can be attributed to Béla Barényi in 1925, predating Porsche claims by over five years. The result was the Volkswagen Type 1 and the introduction of the Volkswagen brand. Volkswagen initially slated production for the late 1930s, but the outbreak of war in 1939 meant that production was delayed until the war had ended. The car was originally called the Volkswagen Type 1 and marketed simply as the Volkswagen, but it was not until 1968 that it was officially named the "Beetle".Volkswagen implemented designations for the Beetle in the 1960s, including 1200, 1300, 1500, 1600, 1302 and 1303. Volkswagen introduced a series of large luxury models throughout the 1960 and 70s—comprising the Type 3, Type 4 and the K70—to supplement the Beetle, but none of these models achieved the level of success that it did. Rapidly changing consumer preferences toward front-wheel drive compact hatchbacks in Europe prompted Volkswagens gradual shift away from rear-wheel drive, starting with the Golf in 1974. In the late 1970s and 80s, Japanese automakers began to dominate the market, which contributed to the Beetles declining popularity.Over its lifespan, the Beetles design remained consistent, yet Volkswagen implemented over 78,000 incremental updates. These modifications were often subtle, involving minor alterations to its exterior, interior, colours, and lighting. Some more noteworthy changes included the introduction of new engines, models and systems, such as improved technology or comfort.', image: 'vw-beetle-405876_1280.jpg' },
    '3': { name: 'Nissan GTR', description: 'The KPGC10 successor, the KPGC110, was introduced in 1973 after its introduction at the 1972 Tokyo Motor Show. Powered by a 1,989 cc S20 inline-6 engine, the second generation of the GT-R delivered power to the rear wheels through a 5-speed manual gearbox. This car also had both front and rear disc brakes. The suspension was a semi-trailing ring arm setup and minor aerodynamic parts were added.This model of the GT-R was also known as the Kenmeri Skyline, due to a popular advertisement featuring a young couple (Ken and Mary) enjoying the Hokkaido countryside. The advertisement later spawned a hit song by Buzz, and the tree featured in the advertisement later became a minor star itself. [citation needed] The second generation GT-R was unsuccessful, as the 1973 oil crisis reduced demand for high-performance sports cars.[16] A total of 197 cars were built by the end of its short production run. For the next decade, this was the last GT-R until the production of the R32 in 1989.', image: 'opel-5190050_1280.jpg' },
    '4': { name: 'Convertible', description: 'A convertible or cabriolet (/ˌkæbrioʊˈleɪ/) is a passenger car that can be driven with or without a roof in place. The methods of retracting and storing the roof vary across eras and manufacturers.A convertible cars design allows an open-air driving experience, with the ability to provide a roof when required. A potential drawback of convertibles is their reduced structural rigidity (requiring significant engineering and modification to counteract the side effects of almost completely removing a cars roof).[2][3]The majority of convertible roofs are of a folding construction framework with the actual top made from cloth or other fabric. Other types of convertible roofs include retractable hardtops (often constructed from metal or plastic) and detachable hardtops (where a metal or plastic roof is manually removed and often stored in the trunk).', image: 'oldtimer-1197800_1280.jpg' },
  };

  const car = cars[carId] || {};

  return (
    <div className="car-details">
      <h1>{car.name}</h1>
      <img src={`/images/${car.image}`} alt={car.name} />
      <p>{car.description}</p>
    </div>
  );
};

export default CarDetails;